### ISSUE TITLE
Common: add .travis.yml file to repo

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1359]
We should test scala-common-enrich as this is the core piece of functionality in the repo...

Don't forget to add (for currency conversion enrichment):

```yaml
env:
global:
- secure: j6RcEPeT5DCmThYA+KSvn5zoFdwhO9Tyk9xXVrW+L8oTTAehDvEWQ1nkJM7m+KYwUtWH1bvRd9IOZgKkWxJeYSDvn8V0zd0dJKSc7R4kykfI/S3V67uM1LCj24B1dF62uiTMOFd9inwB3SLhVFwRk+tcgrZMLs9ljqND77pGR4Y=
```
