### ISSUE TITLE
Common: add Ruby script to generate unified config.yml and iglu-resolver.json from runner.yml and loader.yml

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#1774]
Script should have zero dependencies.

**Comment by fblundun** [comment]
Example of how this script operates:

storage_loader_config.yml:

```
:aws:
  :access_key_id: ADD HERE
  :secret_access_key: ADD HERE
:s3:
  :region: ADD HERE # S3 bucket region
  :buckets:
    :jsonpath_assets: # If you have defined your own JSON Schemas, add the s3:// path to your own JSON Path files in your own bucket here
    :enriched:
      :good: ADD HERE # Must be s3:// not s3n:// for Redshift. This is the same as the :enriched:good: bucket specified for EmrEtlRunner
      :archive: ADD HERE # Where to archive enriched events to
    :shredded:
      :good: ADD HERE # Must be s3:// not s3n:// for Redshift. This is the same as the :shredded:good: bucket specified for EmrEtlRunner
      :archive: ADD HERE # Where to archive shredded types to
:download:
  :folder: # Not required for Redshift
:targets:
  - :name: "My Redshift database"
    :type: redshift
    :host: ADD HERE # The endpoint as shown in the Redshift console
    :database: ADD HERE # Name of database 
    :port: 5439 # Default Redshift port
    :table: atomic.events
    :username: ADD HERE 
    :password: ADD HERE 
    :maxerror: 1 # Stop loading on first error, or increase to permit more load errors
    :comprows: 200000 # Default for a 1 XL node cluster. Not used unless --include compupdate specified
```

eer_config.yml:

```
:logging:
  :level: DEBUG # You can optionally switch to INFO for production
:aws:
  :access_key_id: ADD HERE
  :secret_access_key: ADD HERE
:s3:
  :region: ADD HERE
  :buckets:
    :assets: s3://snowplow-hosted-assets # DO NOT CHANGE unless you are hosting the jarfiles etc yourself in your own bucket
    :log: ADD HERE
    :raw:
      :in: ADD HERE
      :processing: ADD HERE
      :archive: ADD HERE    # e.g. s3://my-archive-bucket/raw
    :enriched:
      :good: ADD HERE       # e.g. s3://my-out-bucket/enriched/good
      :bad: ADD HERE        # e.g. s3://my-out-bucket/enriched/bad
      :errors: ADD HERE     # Leave blank unless :continue_on_unexpected_error: set to true below
    :shredded:
      :good: ADD HERE       # e.g. s3://my-out-bucket/shredded/good
      :bad: ADD HERE        # e.g. s3://my-out-bucket/shredded/bad
      :errors: ADD HERE     # Leave blank unless :continue_on_unexpected_error: set to true below
:emr:
  :ami_version: 3.6.0      # Don't change this
  :region: ADD HERE        # Always set this
  :jobflow_role: EMR_EC2_DefaultRole # Created using $ aws emr create-default-roles
  :service_role: EMR_DefaultRole     # Created using $ aws emr create-default-roles
  :placement: ADD HERE     # Set this if not running in VPC. Leave blank otherwise
  :ec2_subnet_id: ADD HERE # Set this if running in VPC. Leave blank otherwise
  :ec2_key_name: ADD HERE
  :bootstrap: []           # Set this to specify custom boostrap actions. Leave empty otherwise
  :software:
    :hbase:                # To launch on cluster, provide version, "0.92.0", keep quotes
    :lingual:              # To launch on cluster, provide version, "1.1", keep quotes
  # Adjust your Hadoop cluster below
  :jobflow:
    :master_instance_type: m1.small
    :core_instance_count: 2
    :core_instance_type: m1.small
    :task_instance_count: 0 # Increase to use spot instances
    :task_instance_type: m1.small
    :task_instance_bid: 0.015 # In USD. Adjust bid, or leave blank for non-spot-priced (i.e. on-demand) task instances
:etl:
  :job_name: Snowplow ETL # Give your job a name
  :versions:
    :hadoop_enrich: 1.0.0 # Version of the Hadoop Enrichment process
    :hadoop_shred: 0.4.0 # Version of the Hadoop Shredding process
  :collector_format: cloudfront # Or 'clj-tomcat' for the Clojure Collector, or 'thrift' for Thrift records, or 'tsv/com.amazon.aws.cloudfront/wd_access_log' for Cloudfront access logs
  :continue_on_unexpected_error: false # Set to 'true' (and set :out_errors: above) if you don't want any exceptions thrown from ETL
:iglu:
  :schema: iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-0
  :data:
    :cache_size: 500
    :repositories:
      - :name: "Iglu Central"
        :priority: 0
        :vendor_prefixes:
          - com.snowplowanalytics
        :connection:
          :http:
            :uri: http://iglucentral.com
```

Run the command `ruby 3-enrich/emr-etl-runner/config/combine_configurations eer_config.yml storage_loader_config.yml resolver.json combined.yml` and get the following 2 files:

resolver.json:

```
{
  "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-0",
  "data": {
    "cache_size": 500,
    "repositories": [
      {
        "name": "Iglu Central",
        "priority": 0,
        "vendor_prefixes": [
          "com.snowplowanalytics"
        ],
        "connection": {
          "http": {
            "uri": "http://iglucentral.com"
          }
        }
      }
    ]
  }
}
```

combined.yml:

```
---
aws:
  access_key_id: ADD HERE
  secret_access_key: ADD HERE
  s3:
    region: ADD HERE
    buckets:
      assets: s3://snowplow-hosted-assets
      log: ADD HERE
      raw:
        in:
        - ADD HERE
        processing: ADD HERE
        archive: ADD HERE
      enriched:
        good: ADD HERE
        bad: ADD HERE
        errors: ADD HERE
        archive: ADD HERE
      shredded:
        good: ADD HERE
        bad: ADD HERE
        errors: ADD HERE
        archive: ADD HERE
      jsonpath_assets:
  emr:
    ami_version: 3.6.0
    region: ADD HERE
    jobflow_role: EMR_EC2_DefaultRole
    service_role: EMR_DefaultRole
    placement: ADD HERE
    ec2_subnet_id: ADD HERE
    ec2_key_name: ADD HERE
    bootstrap: []
    software:
      hbase:
      lingual:
    jobflow:
      master_instance_type: m1.small
      core_instance_count: 2
      core_instance_type: m1.small
      task_instance_count: 0
      task_instance_type: m1.small
      task_instance_bid: 0.015
    bootstrap_failure_tries: 3
collectors:
  format: cloudfront
enrich:
  job_name: Snowplow ETL
  versions:
    hadoop_enrich: 1.0.0
    hadoop_shred: 0.4.0
  continue_on_unexpected_error: false
  output_compression: NONE
storage:
  download:
    folder:
  targets:
  - name: My Redshift database
    type: redshift
    host: ADD HERE
    database: ADD HERE
    port: 5439
    table: atomic.events
    username: ADD HERE
    password: ADD HERE
    maxerror: 1
    comprows: 200000
monitoring:
  tags: {}
  logging:
    level: DEBUG
  snowplow:
```
