### ISSUE TITLE
Unexpected error: can't convert nil into String

### ISSUE THREAD

**Issue by mitulshah44** [snowplow/snowplow#2224]
```
root@ip-12-31-4-56:~/snowplow/4-storage/storage-loader# cat config/config.yml | ./deploy/snowplow-storage-loader --config -
Unexpected error: can't convert nil into String
org/jruby/RubyFileTest.java:95:in `directory?'
org/jruby/RubyFileTest.java:87:in `directory?'
/root/snowplow/4-storage/storage-loader/deploy/snowplow-storage-loader!/storage-loader/lib/snowplow-storage-loader/config.rb:75:in `get_config'
file:/root/snowplow/4-storage/storage-loader/deploy/snowplow-storage-loader!/storage-loader/bin/snowplow-storage-loader:31:in `(root)'
org/jruby/RubyKernel.java:1091:in `load'
file:/root/snowplow/4-storage/storage-loader/deploy/snowplow-storage-loader!/META-INF/main.rb:1:in `(root)'
org/jruby/RubyKernel.java:1072:in `require'
file:/root/snowplow/4-storage/storage-loader/deploy/snowplow-storage-loader!/META-INF/main.rb:1:in `(root)'
/tmp/jruby2582998318133698724extract/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
```

getting issue by running by storageloader. please suggest me solution. I don't know ruby.

**Comment by mitulshah44** [comment]
My EmrEtlRunner config.yml file:

```
logging:
  level: DEBUG # You can optionally switch to INFO for production
aws:
  # Credentials can be hardcoded or set in environment variables
  access_key_id: AK*****ZA
  secret_access_key: Ro*******toZ
  s3:
    region: us-east-1
    buckets:
      assets: s3://snowplow-hosted-assets # DO NOT CHANGE unless you are hosting the jarfiles etc yourself in your own bucket
      jsonpath_assets: # If you have defined your own JSON Schemas, add the s3:// path to your own JSON Path files in your own bucket here
      log: s3n://mf-snowplow-logs
      raw:
        in:
          - s3n://mf-snowplow-logs        # e.g. s3://my-archive-bucket/raw
        processing: s3n://mf-snowplow-logs/processing
        archive: s3://mf-snowplow-archive/raw    # e.g. s3://my-archive-bucket/raw
      enriched:
        good: s3://mf-snowplow-out/enriched/good       # e.g. s3://my-out-bucket/enriched/good
        bad: s3://mf-snowplow-out/enriched/bad        # e.g. s3://my-out-bucket/enriched/bad
        errors: s3://mf-snowplow-out/enriched/errors     # Leave blank unless :continue_on_unexpected_error: set to true below
        archive: s3://mf-snowplow-out/enriched/archive  # Where to archive enriched events to, e.g. s3://my-out-bucket/enriched/archive
      shredded:
        good: s3://mf-snowplow-out/shredded/good       # e.g. s3://my-out-bucket/shredded/good
         bad: s3://mf-snowplow-out/shredded/bad        # e.g. s3://my-out-bucket/shredded/bad
        errors: s3://mf-snowplow-out/shredded/errors     # Leave blank unless :continue_on_unexpected_error: set to true below
#        archive: s3://metafunding-snowplow-emretlrunner/shredded/archive    # Not required for Postgres currently
  emr:
    ami_version: 3.7.0      # Don't change this
    region: us-east-1        # Always set this
    jobflow_role: EMR_EC2_DefaultRole # Created using $ aws emr create-default-roles
    service_role: EMR_DefaultRole     # Created using $ aws emr create-default-roles
    placement: us-east-1c     # Set this if not running in VPC. Leave blank otherwise
    ec2_subnet_id: subnet-e904f6b0  # Set this if running in VPC. Leave blank otherwise
    ec2_key_name: demo-iqr-snowplow
    bootstrap: []           # Set this to specify custom boostrap actions. Leave empty otherwise
    software:
      hbase:                # To launch on cluster, provide version, "0.92.0", keep quotes
      lingual:              # To launch on cluster, provide version, "1.1", keep quotes
    # Adjust your Hadoop cluster below
    jobflow:
      master_instance_type: m1.medium
      core_instance_count: 2
      core_instance_type: m1.medium
      task_instance_count: 0 # Increase to use spot instances
      task_instance_type: m1.medium
      task_instance_bid: 0.015 # In USD. Adjust bid, or leave blank for non-spot-priced (i.e. on-demand) task instances
    bootstrap_failure_tries: 3 # Number of times to attempt the job in the event of bootstrap failures
collectors:
  format: cloudfront # Or 'clj-tomcat' for the Clojure Collector, or 'thrift' for Thrift records, or 'tsv/com.amazon.aws.cloudfront/wd_access_log' for Cloudfront access logs
enrich:
  job_name: Snowplow ETL # Give your job a name
  versions:
    hadoop_enrich: 1.2.0 # Version of the Hadoop Enrichment process
    hadoop_shred: 0.5.0 # Version of the Hadoop Shredding process
  continue_on_unexpected_error: false # Set to 'true' (and set :out_errors: above) if you don't want any exceptions thrown from ETL
  output_compression: NONE # Compression only supported with Redshift, set to NONE if you have Postgres targets. Allowed formats: NONE, GZIP
storage:
  download:
    folder: # Postgres-only config option. Where to store the downloaded files. Leave blank for Redshift
  targets:
  format: cloudfront # Or 'clj-tomcat' for the Clojure Collector, or 'thrift' for Thrift records, or 'tsv/com.amazon.aws.cloudfront/wd_access_log' for Cloudfront access logs
enrich:
  job_name: Snowplow ETL # Give your job a name
  versions:
    hadoop_enrich: 1.2.0 # Version of the Hadoop Enrichment process
    hadoop_shred: 0.5.0 # Version of the Hadoop Shredding process
  continue_on_unexpected_error: false # Set to 'true' (and set :out_errors: above) if you don't want any exceptions thrown from ETL
  output_compression: NONE # Compression only supported with Redshift, set to NONE if you have Postgres targets. Allowed formats: NONE, GZIP
storage:
  download:
    folder: # Postgres-only config option. Where to store the downloaded files. Leave blank for Redshift
  targets:
    - name: "My PostgreSQL database"
      type: postgres
      host: 127.0.0.1 # Hostname of database server
      database: snowplow # Name of database
      port: 5432 # Default Postgres port
      ssl_mode: disable # One of disable (default), require, verify-ca or verify-full
      table: atomic.events
      username: power_user
      password: password
      maxerror: # Not required for Postgres
      comprows: # Not required for Postgres
monitoring:
  tags: {} # Name-value pairs describing this job
  logging:
    level: DEBUG # You can optionally switch to INFO for production
  snowplow:
    method: get
    app_id: snowplow12 # e.g. snowplow
    collector: dlf****1m3.cloudfront.net 
```

I'm using same config file for storageloader. Is anything missed or wrong ?

**Comment by fblundun** [comment]
Hi @mitulshah44 ,

If you want to load Postgres locally you need to set the `storage.download.folder` field in your . At the moment you have left this blank, causing the above error.

If you want to load Redshift rather than another Postgres database, you need to remove all targets with type "postgres" from the `targets` field in your configuration YAML.

**Comment by mitulshah44** [comment]
what should I put in storage.download.folder? I'm using PostgreSQL setting up in same AWS EC2 instance. 
can you please provide me one example for it?

**Comment by fblundun** [comment]
```yaml
storage:
  download:
    folder: mydownloadfolder
```

You will have to ensure that the `mydownloadfolder` directory exists. You don't have to put anything in it yourself.
