### ISSUE TITLE
Snowplow::EmrEtlRunner::DirectoryNotEmptyError (Should not stage files for enrichment, processing bucket s3n://mf-snowplow-logs/processing/ is not empty)

### ISSUE THREAD

**Issue by mitulshah44** [snowplow/snowplow#2228]
The process was running smoothly for last week, suddenly I saw the raw:in:processing directory is full of files having yesterday's date. So, something should be wrong yesterday, I've changed in the code for last week. I'm getting error today 

raw:in:processing directory should empty automatically using snowplow script, what the issue behind of this issue?

```
root@ip-172-31-4-56:/home/ubuntu/snowplow/3-enrich/emr-etl-runner# ./deploy/snowplow-emr-etl-runner  --config config/config.yml --resolver config/resolver.json 
D, [2015-12-07T07:50:08.510000 #9948] DEBUG -- : Staging CloudFront logs...
F, [2015-12-07T07:50:13.465000 #9948] FATAL -- : 

Snowplow::EmrEtlRunner::DirectoryNotEmptyError (Should not stage files for enrichment, processing bucket s3n://mf-snowplow-logs/processing/ is not empty):
    /home/ubuntu/snowplow/3-enrich/emr-etl-runner/deploy/snowplow-emr-etl-runner!/emr-etl-runner/lib/snowplow-emr-etl-runner/s3_tasks.rb:100:in `stage_logs_for_emr'
    /home/ubuntu/snowplow/3-enrich/emr-etl-runner/deploy/snowplow-emr-etl-runner!/emr-etl-runner/lib/snowplow-emr-etl-runner/runner.rb:51:in `run'
    /usr/local/rvm/gems/jruby-1.7.19/gems/contracts-0.7/lib/contracts/method_reference.rb:46:in `send_to'
    /usr/local/rvm/gems/jruby-1.7.19/gems/contracts-0.7/lib/contracts.rb:305:in `call_with'
    /usr/local/rvm/gems/jruby-1.7.19/gems/contracts-0.7/lib/contracts/decorators.rb:159:in `common_method_added'
    file:/home/ubuntu/snowplow/3-enrich/emr-etl-runner/deploy/snowplow-emr-etl-runner!/emr-etl-runner/bin/snowplow-emr-etl-runner:39:in `(root)'
    org/jruby/RubyKernel.java:1091:in `load'
    file:/home/ubuntu/snowplow/3-enrich/emr-etl-runner/deploy/snowplow-emr-etl-runner!/META-INF/main.rb:1:in `(root)'
    org/jruby/RubyKernel.java:1072:in `require'
    file:/home/ubuntu/snowplow/3-enrich/emr-etl-runner/deploy/snowplow-emr-etl-runner!/META-INF/main.rb:1:in `(root)'
    /tmp/jruby4800438985744883089extract/jruby-stdlib-1.7.20.1.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'

```

Here is the yml file for same

```
logging:
  level: DEBUG # You can optionally switch to INFO for production
aws:
  # Credentials can be hardcoded or set in environment variables
  access_key_id: key
  secret_access_key: secret_key
  s3:
    region: us-east-1
    buckets:
      assets: s3://snowplow-hosted-assets # DO NOT CHANGE unless you are hosting the jarfiles etc yourself in your own bucket
      jsonpath_assets: # If you have defined your own JSON Schemas, add the s3:// path to your own JSON Path files in your own bucket here
      log: s3n://mf-snowplow-logs
      raw:
        in:
          - s3n://mf-snowplow-logs        # e.g. s3://my-archive-bucket/raw
        processing: s3n://mf-snowplow-logs/processing
        archive: s3://mf-snowplow-archive/raw    # e.g. s3://my-archive-bucket/raw
      enriched:
        good: s3://mf-snowplow-out/enriched/good       # e.g. s3://my-out-bucket/enriched/good
        bad: s3://mf-snowplow-out/enriched/bad        # e.g. s3://my-out-bucket/enriched/bad
        errors: s3://mf-snowplow-out/enriched/errors     # Leave blank unless :continue_on_unexpected_error: set to true below
        archive: s3://mf-snowplow-out/enriched/archive  # Where to archive enriched events to, e.g. s3://my-out-bucket/enriched/archive
      shredded:
        good: s3://mf-snowplow-out/shredded/good  
        bad: s3://mf-snowplow-out/shredded/bad        # e.g. s3://my-out-bucket/shredded/bad
        errors: s3://mf-snowplow-out/shredded/errors     # Leave blank unless :continue_on_unexpected_error: set to true below
#        archive:   # Not required for Postgres currently
  emr:
    ami_version: 3.7.0      # Don't change this
    region: us-east-1        # Always set this
    jobflow_role: EMR_EC2_DefaultRole # Created using $ aws emr create-default-roles
    service_role: EMR_DefaultRole     # Created using $ aws emr create-default-roles
    placement: us-east-1c     # Set this if not running in VPC. Leave blank otherwise
    ec2_subnet_id: subnet-e904f6b0  # Set this if running in VPC. Leave blank otherwise
    ec2_key_name: demo-iqr-snowplow
    bootstrap: []           # Set this to specify custom boostrap actions. Leave empty otherwise
    software:
      hbase:                # To launch on cluster, provide version, "0.92.0", keep quotes
      lingual:              # To launch on cluster, provide version, "1.1", keep quotes
    # Adjust your Hadoop cluster below
    jobflow:
      master_instance_type: m1.medium
      core_instance_count: 2
      core_instance_type: m1.medium
      task_instance_count: 0 # Increase to use spot instances
      task_instance_type: m1.medium
      task_instance_bid: 0.015 # In USD. Adjust bid, or leave blank for non-spot-priced (i.e. on-demand) task instances
    bootstrap_failure_tries: 3 # Number of times to attempt the job in the event of bootstrap failures
collectors:
  format: cloudfront # Or 'clj-tomcat' for the Clojure Collector, or 'thrift' for Thrift records, or 'tsv/com.amazon.aws.cloudfront/wd_access_log' for Cloudfront access logs
enrich:
  job_name: Snowplow ETL # Give your job a name
  versions:
    hadoop_enrich: 1.2.0 # Version of the Hadoop Enrichment process
    hadoop_shred: 0.5.0 # Version of the Hadoop Shredding process
  continue_on_unexpected_error: false # Set to 'true' (and set :out_errors: above) if you don't want any exceptions thrown from ETL
  output_compression: NONE # Compression only supported with Redshift, set to NONE if you have Postgres targets. Allowed formats: NONE, GZIP
storage:
  download:
    folder: /home/ubuntu/snowflow/mydownloadfolder  # Postgres-only config option. Where to store the downloaded files. Leave blank for Redshift
  targets:
    - name: "My PostgreSQL database"
      type: postgres
      host: 127.0.0.1 # Hostname of database server
      database: snowplow # Name of database
      port: 5432 # Default Postgres port
      ssl_mode: disable # One of disable (default), require, verify-ca or verify-full
      table: atomic.events
      username: usr
      password: ####
      maxerror: # Not required for Postgres
      comprows: # Not required for Postgres
monitoring:
  tags: {} # Name-value pairs describing this job
  logging:
    level: DEBUG # You can optionally switch to INFO for production
  snowplow:
    method: get
    app_id: snowplow12 # e.g. snowplow
    collector: dlfdfdfsg01m3.cloudfront.net  # e.g. d3rkrsqld9gmqf.cloudfront.net
                                                                                                      
```
