### ISSUE TITLE
EmrEtlRunner: update archive bucket examples in config.yml

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#2368]
From:

```yaml
archive: ADD HERE    # Where to archive enriched events to, e.g. s3://my-out-bucket/enriched/archive
...
archive: ADD HERE    # Not required for Postgres currently
```

to:

```yaml
archive: ADD HERE    # Where to archive enriched events to, e.g. s3://my-archive-bucket/enriched
...
archive: ADD HERE    # Where to archive shredded events to, e.g. s3://my-archive-bucket/shredded
```

/cc @ihortom
