### ISSUE TITLE
EmrEtlRunner: add support for specifying EBS for Hadoop workers

### ISSUE THREAD

**Issue by estahn** [snowplow/snowplow#2950]
We currently running out of space and the only option seems to be a bigger instance size.

It would be great to be able to define the size of the EBS volume in the config:
```
core_instance_count: 3
core_instance_type: c4.2xlarge
core_instance_ebs:
  volume_size: 2000
  volume_type: gp2
```

https://aws.amazon.com/blogs/aws/amazon-emr-update-support-for-ebs-volumes-and-m4-c4-instance-types/
