### ISSUE TITLE
EmrEtlRunner: expose arbitrary EMR configuration options

### ISSUE THREAD

**Issue by BenFradet** [snowplow/snowplow#3255]
translates to:

```yaml
aws:
  emr:
    configuration:
      yarn-site:
         yarn.resourcemanager.am.max-attempts: 1
      spark:
         maximizeResourceAllocation: true
      spark-defaults:
         spark.executor.instances: 17
         spark.yarn.executor.memoryOverhead: 4096
         spark.executor.memory: 35G
         spark.yarn.driver.memoryOverhead: 4096
```
