### ISSUE TITLE
enricher, loader, and mutator have defective health endpoints

### ISSUE THREAD

**Issue by mabushey** [snowplow/snowplow#4514]
This issue does not appear to apply to collector and repeator. In a GKE k8s cluster (v1.20.8-gke.2100), enricher, loader, and mutator all give `Liveness probe failed: HTTP probe failed with statuscode: 500` within a minute or two.
```
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
```

Is /health on 8080 the wrong endpoint or are the services just locking up every couple of minutes?

- image: snowplow/snowplow-enrich-pubsub:2.0.2
- image: snowplow/snowplow-bigquery-streamloader:0.6.4
- image: snowplow/snowplow-bigquery-mutator:0.6.4

**Comment by mabushey** [comment]
I guess they literally don't have health endpoints. Unfortunately I'm running on GKE which has no clue when a preemptable node goes away. The containers don't even have `ps` installed, so I'm just using this:
```
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - /bin/hostname
            initialDelaySeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
```
