### ISSUE TITLE
EmrEtlRunner: add support for Elasticsearch in targets section of config.yml

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/snowplow#826]
Something like this:

```yaml
targets:
  - name: "My ElasticSearch cluster"
    type: elasticsearch
    host: ADD HERE # Hostname of database server
    database: ADD HERE # Name of database 
    port: 9200 # Default ElasticSearch port
    table: bad_rows
```

**Comment by fblundun** [comment]
It probably wouldn't be table - would probably be type (assuming that doesn't break Contracts!)

**Comment by fblundun** [comment]
The dual meaning of "type" here is pretty inconvenient. Perhaps we should start using "type" to mean the Elasticsearch type and replace "type: redshift" with something else, e.g. "target_kind: redshift"?

**Comment by alexanderdean** [comment]
There's another question here which is around how we express which type (sorry) of data (enriched events or bad rows) is being stored in the target. It feels like we should be explicit about this. Let's brainstorm all this when I'm in...

**Comment by fblundun** [comment]
How about something like

```yml
  - name: myelasticsearch
    type: elasticsearch
    host: myhost
    database: mydatabase
    port: 9200
    table: badrows
    sources: ["s3://path/run=xx", "s3://path/run=xx"]
```

Where "sources" is an array of all the buckets containing bad rows which you want to send to Elasticsearch.

If the "sources" field isn't given, it would default to the two bad rows buckets for the current run (enrich failures and shred failures).

**Comment by fblundun** [comment]
We should probably add an option to toggle connecting only to declared es.nodes (this would be true for AES and false otherwise):

```yml
  - name: myelasticsearch
    type: elasticsearch
    host: myhost
    database: mydatabase
    port: 9200
    table: badrows
    sources: ["s3://path/run=xx", "s3://path/run=yy"]
    "es.nodes.wan.only": true # allows writing to AES
```
